# MyOS uses the Limine protocol only to enter our own x86_64 kernel.
timeout: 0

/MyOS 0.12.2-dev (x86_64)
    protocol: limine
    path: boot():/boot/kernel.elf
    module_path: boot():/boot/initramfs.cpio
    module_string: initramfs
